export { default as Home } from './Home'
export { default as Onboarding } from './Onboarding'
export { default as ViewMore } from './ViewMore'
export { default as Info } from './Info'
export { default as NotFound } from './NotFound'